### ISSUE TITLE
Take over maintenance? 

### ISSUE THREAD

**Issue by raycharius** [matiassingers/awesome-slack#32]
Hi there! 

This like it was once something really awesome :) I've noticed it's not maintained anymore, and since the last commits, Slack has grown so much. 

Would be happy to become a maintainer, update it, and keep it going.

Thoughts?

**Comment by matiassingers** [comment]
That would be awesome @raycharius - I've been falling behind on keeping this updated.

I've added you as a maintainer now, thanks!

**Comment by raycharius** [comment]
Thanks! Will work on getting it up to date this week :)
